# UNCOMMENT THE BELOW REQUESTS ONE BY ONE AND 
# CLICK ON THE SEND REQUEST BUTTON TO OBSERVE THE OUTPUT

# POST http://localhost:3000/session


# GET http://localhost:3000/session


# PUT http://localhost:3000/update-session


# DELETE http://localhost:3000/delete-session

